import {
  Anvil,
  Archive,
  BrickWall,
  Building,
  Building2,
  Castle,
  Church,
  Cookie,
  Dam,
  Factory,
  Fence,
  GraduationCap,
  Hospital,
  Hotel,
  House,
  HouseHeart,
  HousePlug,
  HousePlus,
  HouseWifi,
  Landmark,
  School,
  Store,
  Theater,
  University,
  UtilityPole,
  Warehouse,
} from 'lucide-react';
import type { IconEntry } from './LucideIcon';

export const iconRegistry: IconEntry[] = [
  {
    name: 'anvil',
    component: Anvil,
    descriptionEs: 'Yunque; forja, herrería, trabajo manual o industria pesada.',
    descriptionEn: 'Anvil; forge, blacksmith, manual work or heavy industry.',
    keywordsEs: 'yunque, forja, herrería, industria, metal, martillo',
    keywordsEn: 'anvil, forge, blacksmith, industry, metal, hammer',
  },
  {
    name: 'archive',
    component: Archive,
    descriptionEs: 'Caja de archivo; guardar, almacenar o archivar documentos y elementos.',
    descriptionEn: 'Archive box; save, store, or archive documents and items.',
    keywordsEs: 'archivo, caja, almacenar, guardar, documentos, archivar',
    keywordsEn: 'archive, box, store, save, documents, file',
  },
  {
    name: 'brick-wall',
    component: BrickWall,
    descriptionEs: 'Muro de ladrillos; construcción, barrera, mamposteríao estructura.',
    descriptionEn: 'Brick wall; construction, barrier, masonry or structure.',
    keywordsEs: 'ladrillo, muro, pared, construcción, barrera, mampostería',
    keywordsEn: 'brick, wall, construction, barrier, masonry, structure',
  },
  {
    name: 'building',
    component: Building,
    descriptionEs: 'Edificio de oficinas; negocio, empresa, inmueble o trabajo.',
    descriptionEn: 'Office building; business, company, real estate or work.',
    keywordsEs: 'edificio, oficina, empresa, negocio, inmueble, trabajo',
    keywordsEn: 'building, office, company, business, real estate, work',
  },
  {
    name: 'building-2',
    component: Building2,
    descriptionEs: 'Edificio alternativo; sede, corporación, ciudad o inmueble.',
    descriptionEn: 'Alternative building; headquarters, corporation, city or real estate.',
    keywordsEs: 'edificio, sede, corporación, ciudad, inmueble, oficina',
    keywordsEn: 'building, headquarters, corporation, city, real estate, office',
  },
  {
    name: 'castle',
    component: Castle,
    descriptionEs: 'Castillo; historia, medievalismo, fortaleza o fantasía.',
    descriptionEn: 'Castle; history, medieval, fortress or fantasy.',
    keywordsEs: 'castillo, fortaleza, medieval, historia, torre, fantasía',
    keywordsEn: 'castle, fortress, medieval, history, tower, fantasy',
  },
  {
    name: 'church',
    component: Church,
    descriptionEs: 'Iglesia; religión, culto, comunidad o espiritualidad.',
    descriptionEn: 'Church; religion, worship, community or spirituality.',
    keywordsEs: 'iglesia, religión, culto, capilla, catedral, fe',
    keywordsEn: 'church, religion, worship, chapel, cathedral, faith',
  },
  {
    name: 'cookie',
    component: Cookie,
    descriptionEs: 'Galleta; dulce, repostería, cookies del navegador o preferencias.',
    descriptionEn: 'Cookie; sweet, baked treat, browser cookies or preferences.',
    keywordsEs: 'galleta, cookie, dulce, repostería, navegador, preferencias',
    keywordsEn: 'cookie, biscuit, sweet, browser, preferences, treat',
  },
  {
    name: 'dam',
    component: Dam,
    descriptionEs: 'Presa o embalse; agua, energía hidráulica o infraestructura.',
    descriptionEn: 'Dam; water, hydroelectric power or infrastructure.',
    keywordsEs: 'presa, embalse, agua, hidráulica, energía, infraestructura',
    keywordsEn: 'dam, reservoir, water, hydroelectric, energy, infrastructure',
  },
  {
    name: 'factory',
    component: Factory,
    descriptionEs: 'Fábrica; manufactura, industria, producción o planta industrial.',
    descriptionEn: 'Factory; manufacturing, industry, production or industrial plant.',
    keywordsEs: 'fábrica, industria, manufactura, planta, producción, chimenea',
    keywordsEn: 'factory, industry, manufacturing, plant, production, chimney',
  },
  {
    name: 'fence',
    component: Fence,
    descriptionEs: 'Valla o cerca; límite, propiedad, jardín o seguridad.',
    descriptionEn: 'Fence; boundary, property, garden or security.',
    keywordsEs: 'valla, cerca, límite, propiedad, jardín, seguridad',
    keywordsEn: 'fence, boundary, property, garden, security, barrier',
  },
  {
    name: 'graduation-cap',
    component: GraduationCap,
    descriptionEs: 'Birrete de graduación; educación, universidad, logro o diploma.',
    descriptionEn: 'Graduation cap; education, university, achievement or diploma.',
    keywordsEs: 'birrete, graduación, educación, universidad, diploma, logro',
    keywordsEn: 'graduation, cap, education, university, diploma, achievement',
  },
  {
    name: 'hospital',
    component: Hospital,
    descriptionEs: 'Hospital; salud, medicina, urgencias o atención médica.',
    descriptionEn: 'Hospital; health, medicine, emergency or medical care.',
    keywordsEs: 'hospital, salud, medicina, urgencias, clínica, médico',
    keywordsEn: 'hospital, health, medicine, emergency, clinic, doctor',
  },
  {
    name: 'hotel',
    component: Hotel,
    descriptionEs: 'Hotel; alojamiento, viaje, hospedaje o turismo.',
    descriptionEn: 'Hotel; accommodation, travel, lodging or tourism.',
    keywordsEs: 'hotel, alojamiento, viaje, hospedaje, turismo, habitación',
    keywordsEn: 'hotel, accommodation, travel, lodging, tourism, room',
  },
  {
    name: 'house',
    component: House,
    descriptionEs: 'Casa o vivienda; hogar, inicio, residencia o inmueble.',
    descriptionEn: 'House; home, start, residence or real estate.',
    keywordsEs: 'casa, hogar, vivienda, inicio, residencia, inmueble',
    keywordsEn: 'house, home, start, residence, real estate, dwelling',
  },
  {
    name: 'house-heart',
    component: HouseHeart,
    descriptionEs: 'Casa con corazón; hogar amado, propiedad favorita o bienvenida.',
    descriptionEn: 'House with heart; beloved home, favorite property or welcome.',
    keywordsEs: 'casa, corazón, hogar, amor, favorito, bienvenida',
    keywordsEn: 'house, heart, home, love, favorite, welcome',
  },
  {
    name: 'house-plug',
    component: HousePlug,
    descriptionEs: 'Casa con enchufe; hogar inteligente, domótica o energía en casa.',
    descriptionEn: 'House with plug; smart home, home automation or home energy.',
    keywordsEs: 'casa, enchufe, hogar inteligente, domótica, energía, electricidad',
    keywordsEn: 'house, plug, smart home, automation, energy, electricity',
  },
  {
    name: 'house-plus',
    component: HousePlus,
    descriptionEs: 'Casa con más; añadir hogar, nueva propiedad o ampliar vivienda.',
    descriptionEn: 'House with plus; add home, new property or expand dwelling.',
    keywordsEs: 'casa, añadir, nueva propiedad, ampliar, vivienda, más',
    keywordsEn: 'house, add, new, property, expand, dwelling, plus',
  },
  {
    name: 'house-wifi',
    component: HouseWifi,
    descriptionEs: 'Casa con wifi; hogar conectado, red doméstica o internet en casa.',
    descriptionEn: 'House with wifi; connected home, home network or home internet.',
    keywordsEs: 'casa, wifi, hogar conectado, red, internet, domótica',
    keywordsEn: 'house, wifi, connected home, network, internet, smart',
  },
  {
    name: 'landmark',
    component: Landmark,
    descriptionEs: 'Monumento o punto de referencia; lugar histórico, banco o institución.',
    descriptionEn: 'Landmark; historic site, bank, government or institution.',
    keywordsEs: 'monumento, referencia, histórico, banco, institución, columnas',
    keywordsEn: 'landmark, monument, historic, bank, government, institution',
  },
  {
    name: 'school',
    component: School,
    descriptionEs: 'Escuela; educación, colegio, aprendizaje o enseñanza.',
    descriptionEn: 'School; education, learning, teaching or academic.',
    keywordsEs: 'escuela, colegio, educación, aprendizaje, enseñanza, aula',
    keywordsEn: 'school, education, learning, teaching, academic, class',
  },
  {
    name: 'store',
    component: Store,
    descriptionEs: 'Tienda o comercio; venta, compra, negocio o establecimiento.',
    descriptionEn: 'Store or shop; retail, purchase, business or establishment.',
    keywordsEs: 'tienda, comercio, venta, compra, negocio, establecimiento',
    keywordsEn: 'store, shop, retail, purchase, business, establishment',
  },
  {
    name: 'theater',
    component: Theater,
    descriptionEs: 'Teatro; artes escénicas, espectáculo, drama o entretenimiento.',
    descriptionEn: 'Theater; performing arts, show, drama or entertainment.',
    keywordsEs: 'teatro, artes, espectáculo, drama, entretenimiento, máscaras',
    keywordsEn: 'theater, arts, show, drama, entertainment, masks',
  },
  {
    name: 'university',
    component: University,
    descriptionEs: 'Universidad; educación superior, campus, institución académica.',
    descriptionEn: 'University; higher education, campus, academic institution.',
    keywordsEs: 'universidad, educación superior, campus, academia, institución',
    keywordsEn: 'university, higher education, campus, academic, institution',
  },
  {
    name: 'utility-pole',
    component: UtilityPole,
    descriptionEs: 'Poste de electricidad; tendido eléctrico, infraestructura o suministro.',
    descriptionEn: 'Utility pole; power line, infrastructure or utility supply.',
    keywordsEs: 'poste, electricidad, tendido, infraestructura, suministro, cable',
    keywordsEn: 'utility pole, power line, electricity, infrastructure, supply, cable',
  },
  {
    name: 'warehouse',
    component: Warehouse,
    descriptionEs: 'Almacén o nave industrial; logística, depósito, inventario o distribución.',
    descriptionEn: 'Warehouse; logistics, storage, inventory or distribution.',
    keywordsEs: 'almacén, nave, logística, depósito, inventario, distribución',
    keywordsEn: 'warehouse, logistics, storage, inventory, distribution, depot',
  },
];

export type LucideName = (typeof iconRegistry)[number]['name'];
